# http port set
server:
  port: 8082
  
spring:
  # File Size
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # Oracle Connect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: S20220101
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
  # ORM JPA
  jpa:
    hibernate:
      ddl-auto: none # create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
  # gmail Transfer
  mail: 
    host: smtp.gmail.com
    port: 587
    username: //불법적인 구글 로그인 시도가 있었습니다.
    password: //구글에 신고조치 했으니 사용하신 분은 개인적으로 연락바랍니다.
    properties: 
      mail:
        smtp:
          auth: true
          starttls.enable: true
        
  # view resolver(Template -> JSP Use)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
# Mybatis
mybatis:
  # dto Location
  type-aliases-package: com.oracle.BlockBuster.model
  # xml Location
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml      